name: Deploy to S3
on:
  push:
    branches:
      - main # Se dispara al hacer push a la rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configura el entorno de Node (si es necesario construir la app)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3. Instala dependencias y genera los archivos de producci√≥n
      - name: Install and Build
        run: |
          npm install
          npm run build  # Esto genera la carpeta /dist o /build

      # 4. Configura las credenciales de AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5. Sincroniza la carpeta generada con el bucket de S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete
